-- Member card sale/refund business tables.
-- Status: member_card.status 0=pending, 1=active, 2=expired, 3=refunded.

create table if not exists member_card (
    id bigint primary key auto_increment,
    member_id int not null,
    member_no varchar(50) not null,
    card_type_id int not null,
    card_type_name varchar(100) not null,
    valid_days int not null,
    sale_amount decimal(10,2) not null default 0.00,
    sale_order_no varchar(64) not null,
    status tinyint not null default 0,
    paid_at datetime not null,
    effective_at datetime null,
    expired_at datetime null,
    refunded_at datetime null,
    refund_order_no varchar(64) null,
    dept_id bigint null,
    create_staff_id varchar(64) null,
    create_staff_name varchar(64) null,
    remark varchar(500) null,
    created_at datetime not null default current_timestamp,
    updated_at datetime null default current_timestamp on update current_timestamp,
    is_del tinyint not null default 0,
    unique key uk_member_card_sale_order_no (sale_order_no),
    key idx_member_card_member_status_paid (member_id, status, paid_at, id),
    key idx_member_card_expired_at (expired_at),
    key idx_member_card_refund_order_no (refund_order_no)
) engine=InnoDB default charset=utf8mb4 comment='member card instance';

create table if not exists member_card_order (
    id bigint primary key auto_increment,
    order_no varchar(64) not null,
    member_card_id bigint null,
    member_id int not null,
    member_no varchar(50) not null,
    member_name varchar(100) null,
    member_phone varchar(32) null,
    card_type_id int not null,
    card_type_name varchar(100) not null,
    valid_days int not null,
    receivable_amount decimal(10,2) not null default 0.00,
    paid_amount decimal(10,2) not null default 0.00,
    payment_type varchar(32) not null,
    order_status tinyint not null default 1,
    pay_time datetime not null,
    dept_id bigint null,
    create_staff_id varchar(64) null,
    create_staff_name varchar(64) null,
    remark varchar(500) null,
    created_at datetime not null default current_timestamp,
    updated_at datetime null default current_timestamp on update current_timestamp,
    is_del tinyint not null default 0,
    unique key uk_member_card_order_no (order_no),
    unique key uk_member_card_order_card_id (member_card_id),
    key idx_member_card_order_member (member_id, pay_time),
    key idx_member_card_order_pay_time (pay_time)
) engine=InnoDB default charset=utf8mb4 comment='member card sale order';

create table if not exists member_card_refund_order (
    id bigint primary key auto_increment,
    refund_order_no varchar(64) not null,
    sale_order_no varchar(64) not null,
    member_card_id bigint not null,
    member_id int not null,
    member_no varchar(50) not null,
    card_type_id int not null,
    card_type_name varchar(100) not null,
    refund_amount decimal(10,2) not null default 0.00,
    refund_type varchar(32) not null,
    refund_status tinyint not null default 1,
    reason varchar(500) null,
    refund_time datetime not null,
    dept_id bigint null,
    operator_id varchar(64) null,
    operator_name varchar(64) null,
    remark varchar(500) null,
    created_at datetime not null default current_timestamp,
    updated_at datetime null default current_timestamp on update current_timestamp,
    is_del tinyint not null default 0,
    unique key uk_member_card_refund_no (refund_order_no),
    unique key uk_member_card_refund_card_id (member_card_id),
    key idx_member_card_refund_sale_order (sale_order_no),
    key idx_member_card_refund_member (member_id, refund_time)
) engine=InnoDB default charset=utf8mb4 comment='member card refund order';

create table if not exists member_card_biz_log (
    id bigint primary key auto_increment,
    trace_id varchar(64) not null,
    member_card_id bigint null,
    sale_order_no varchar(64) null,
    refund_order_no varchar(64) null,
    member_id int null,
    member_no varchar(50) null,
    log_type varchar(32) not null,
    before_data text null,
    after_data text null,
    change_fields varchar(500) null,
    reason varchar(500) null,
    operator_id varchar(64) null,
    operator_name varchar(64) null,
    device varchar(64) null,
    created_at datetime not null default current_timestamp,
    is_del tinyint not null default 0,
    key idx_member_card_biz_log_card (member_card_id, created_at),
    key idx_member_card_biz_log_order (sale_order_no),
    key idx_member_card_biz_log_refund (refund_order_no),
    key idx_member_card_biz_log_trace (trace_id)
) engine=InnoDB default charset=utf8mb4 comment='member card business log';
